services:
  - type: web
    name: 2match-backend
    env: node
    plan: starter
    region: oregon
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: postgresql://postgres.jjaavtelyfbteukkykkj:Franklineomollo5@aws-1-eu-north-1.pooler.supabase.com:6543/postgres
        fromDatabase:
          name: 2-Match
          property: connectionString
      - key: db1851a076494873628baf7a456f09c369ee94dbe0b6e2b287db654b8ba9f40f0307a6905360e38398c042bb4d491a17768a20eaeb99d5cb54803059265a7ed2
        generateValue: true
      - key: 565a1e1e8bb969807a2a2b3d2e5fc7d75ede5a637820d60cc28858b283f864c8c5295d37f1ac1ab7bc91ed21717145f7533e0bb496763ca9ca9904064d6e6137
        generateValue: true
      - key: PORT
        value: 3000
      # Add your other environment variables here
      - key: dfr07z2c6
        sync: false
      - key: 666683934798426
        sync: false
      - key: TMlf6J_n4ncZh-qEP-U6ns64Ceo
        sync: false
      # - key: REDIS_URL
      #   fromService:
      #     type: redis
      #     name: 2match-redis
      #     property: connectionString
      # - key: SENTRY_DSN
      #   sync: false
      # - key: CORS_ORIGIN
      #   value: https://yourdomain.com
      # - key: FRONTEND_URL
      #   value: https://yourdomain.com

databases:
  - name: 2match-db
    databaseName: 2match
    plan: starter
    region: oregon

# Optional: Add Redis if needed
# - type: redis
#   name: 2match-redis
#   plan: starter
#   region: oregon
#   maxmemoryPolicy: allkeys-lru
